language: node_js
node_js:
  - "lts/boron"  #6.x  - Maintenance LTS
  - "lts/carbon" #8.x  - Active LTS
  - "stable"     #10.x - Current Release
before_install:
  - npm i -g npm@^6
install:
  - npm ci
script:
  - npm run lint
  - npm run build
  - npm run test
