language: node_js
node_js:
  - 'lts/carbon'  #8.x  - Maintenance LTS
  - 'lts/*'       #10.x - Active LTS
  - 'stable'      #12.x - Current Release
before_install:
  - npm i -g npm@^6
install:
  - npm ci
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - npm run coveralls
  